name: Django CI/CD to ECR & EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 \
        | docker login --username AWS --password-stdin 983915441388.dkr.ecr.us-east-1.amazonaws.com

    - name: Build, Tag, and Push Docker image
      run: |
        IMAGE_REPO_NAME=todo_list 
        IMAGE_TAG=latest
        docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
        docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 983915441388.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        docker push 983915441388.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/todo_list.pem
        chmod 600 ~/.ssh/todo_list.pem

        # Use the correct username (ubuntu for Ubuntu AMI, ec2-user for Amazon Linux)
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/todo_list.pem ec2-user@$HOST "echo 'Connected to EC2 ✅'"

        # Pull latest image from ECR
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/todo_list.pem ec2-user@$HOST "docker pull 983915441388.dkr.ecr.us-east-1.amazonaws.com/todo_list:latest"

        # Stop and remove old container if exists
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/todo_list.pem ec2-user@$HOST "docker rm -f todo_container || true"

        # Run new container
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/todo_list.pem ec2-user@$HOST "docker run -d --name todo_container -p 8000:8000 983915441388.dkr.ecr.us-east-1.amazonaws.com/todo_list:latest"
