name: Django CI/CD to ECR & EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 \
        | docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com

    - name: Build, Tag, and Push Docker image
      run: |
        IMAGE_REPO_NAME=todo_list
        IMAGE_TAG=latest
        docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
        docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 983915441388.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        docker push 983915441388.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$HOST << 'EOF'
          aws ecr get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin 983915441388.dkr.ecr.us-east-1.amazonaws.com
          docker pull 983915441388.dkr.ecr.us-east-1.amazonaws.com/todo_list:latest
          docker stop django-app || true
          docker rm django-app || true
          docker run -d -p 8000:8000 --name django-app 983915441388.dkr.ecr.us-east-1.amazonaws.com/todo_list:latest
        EOF
