name: Django CI/CD to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t my-django-app:latest .
        docker tag my-django-app:latest ${{ steps.ecr-login.outputs.registry }}/my-django-app:latest

    - name: Push Docker image to ECR
      run: |
        docker push ${{ steps.ecr-login.outputs.registry }}/my-django-app:latest

    - name: (Optional) Deploy to EC2
      run: |
        ssh -i ${{ secrets.EC2_KEY }} ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          docker pull 983915441388.dkr.ecr.us-east-1.amazonaws.com/my-django-app:latest
          docker stop django-app || true
          docker rm django-app || true
          docker run -d -p 8000:8000 --name django-app 983915441388.dkr.ecr.us-east-1.amazonaws.com/my-django-app:latest
        EOF
